project:
  type: book
  output-dir: docs
book:
  title: "Cell type specific response in disease and intervention"
  subtitle: "With snRNA-seq analysis"
  author: "Ruby Jiang"
  date: "18 April 2023"
  search: true
  cover-image: figures/cover_artremix.png
  repo-url: https://github.com/brainfo/phd_book_quarto/
  repo-actions: [edit]
  site-url: https://brainfo.github.io/book_quarto
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - 1-Preprocess.qmd
    - 2-RNAd.qmd
    - references.qmd

# bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    callout-appearance: simple
  pdf:
    documentclass: krantz
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    keep-tex: true
    callout-appearance: simple



